---
title: "RiberaDeni"
author: "Jianqiu Zheng"
date: "10/9/2020"
output: html_document
---
###creat ODE function with selected output (select the ones with measurements) for optimization purpose
# concentrations all in mM, rates in mM per min
## affinity constant at 10 uM level

```{r kin}
library(FME)

pars<- list (vmax=0.1)

solveDnra <- function(pars, times=seq(0,100, by=0.05)){
  
  derivs <- function(t, state, pars){
      with(as.list(c(state, pars)),{
      r1<-vmax* Nat/(Nat+0.01) * CHO/(CHO+0.01)
      r2<-0.016* Nit/(Nit+0.01) * CHO/(CHO+0.01)
      r3<-0.1* N2O/(N2O+0.01) * CHO/(CHO+0.01)
      rsum<-r1+r2+r3
         #reaction stoichiometry for methanol
      #dNat<- -1.46*r1*r1/rsum
      #dNit<- 1.26*r1*r1/rsum-1.11*r2*r2/rsum
      #dN2O<- 0.46*r2*r2/rsum-0.78*r3*r3/rsum
      #dCHO<- -1.35*r1*r1/rsum-1.17*r2*r2/rsum-1.13*r3*r3/rsum
      
      #reaction stoichiometry for ethanol
      dNat<- -2.07*r1*r1/rsum
      dNit<- 1.87*r1*r1/rsum-1.48*r2*r2/rsum
      dN2O<- 0.64*r2*r2/rsum-1.01*r3*r3/rsum
      dCHO<- -0.78*r1*r1/rsum-0.65*r2*r2/rsum-0.60*r3*r3/rsum
     
       #reaction stoichiometry for acetate
      #dNat<- -2.59*r1*r1/rsum
      #dNit<- 2.39*r1*r1/rsum-1.79*r2
      #dN2O<- 0.8*r2*r2/rsum-1.22*r3*r3/rsum
      #dCHO<- -1.3*r1*r1/rsum-1.05*r2*r2/rsum-0.96*r3*r3/rsum
      
     R1<-r1*r1/rsum/(r1*r1/rsum+r2*r2/rsum+r3*r3/rsum)
     R2<-r2*r2/rsum/(r1*r1/rsum+r2*r2/rsum+r3*r3/rsum)
     R3<-r3*r3/rsum/(r1*r1/rsum+r2*r2/rsum+r3*r3/rsum)
     
    return(list(c(dNat, dNit,dN2O,dCHO), R1, R2, R3))
      })
  }
times=seq(0,100, by=0.02)
state<-c(Nat=1.42, Nit=0, N2O=0, CHO=1.042)
#solved the mode
  ox<-ode(y=state, times=times, func=derivs, parms=pars)

data.frame(ox[,1:8])
}

output<-solveDnra(pars)  
R<-(1.42-output[51,3])
##plotting
#pdf("dnra_cyb_lowCN.pdf", width=5, height=4)
plot(output$time,output$Nat, type = "l",xlab = "Time (min)", ylab = "Concentration (mM)", lwd=3,col="#7f3b08", xlim=c(0,100), ylim=c(0,2))
lines(output$time,output$Nit, lwd=3, col="#e08214")
lines(output$time,output$N2O, lwd=3, col="#fdb863")
legend("topright", c("Nat","Nit","N2O"),lwd=3, lty=c(1,1,1), col=c("#7f3b08","#e08214","#fdb863"))


#pdf("batchF_ace_ratio.pdf", width=5, height=4.5)
plot(output$time,output$X5, type = "l",xlab = "Time (h)", ylab = "Concentration (mM)", lwd=3,col="#7f3b08", xlim=c(0,200), ylim=c(0,1))
lines(output$time,output$X6, lwd=3, col="#e08214")
lines(output$time,output$X7, lwd=3, col="#fdb863")
legend("topright", c("Ace","Eth","Met"),lwd=3, lty=c(1,1,1,2), col=c("#7f3b08","#e08214","#fdb863","#8073ac"))


```

##fitting

```{r data}


Data<-read.csv("Ribera_ethNO3.csv",header=TRUE)

Objective <- function(x, parset = names(x)) {
 pars[parset] <- x
 tout <- seq(0, 100, by = 0.05) ## output times
 out <- solveDnra(pars, tout)
 return(modCost(model = out, obs = Data))## Model cost
}


#parameters are constrained to be >0
print(system.time(Fit <- modFit(p = c(vmax=0.05),
 f = Objective, lower = c(0.0))))

summary(Fit)

```


```{r plot}

pars[c("vmax1","vmax2","vmax3")]<-Fit$par
output<-solveDnra(pars)  

mfit<-as.data.frame(output[, 1:5])
colnames(mfit) <- c("time", "Nat","Nit","N2O","CHO")
head(mfit)



pdf("the_N2O.pdf", width=4, height=4)
plot(Data$time,Data$N2O, xlab = "Time (min)", ylab = "Concentration (mM)", pch=16, cex=1.2,col="#fdb863", xlim=c(0,30), ylim=c(0,2))
lines(mfit$time, mfit$N2O, lwd=2, col="#fdb863")
lines(mfit$time, mfit$CHO, lwd=2, lty=2,col="#542788")
legend("topright", c("N2O","Ethanol"), lwd=2, lty=c(1,2),col=c("#fdb863","#542788"))

dev.off()


pdf("eth_Nit.pdf", width=4, height=4)
plot(Data$time,Data$Nit, xlab = "Time (min)", ylab = "Concentration (mM)", pch=16, cex=1.2,col="#e08214", xlim=c(0,100), ylim=c(0,2))
lines(mfit$time, mfit$Nit, lwd=2, col="#e08214")
#points(Data$time, Data$N2O, pch=16, cex=1.2, col="#fdb863")
lines(mfit$time, mfit$N2O, lwd=2, col="#fdb863")
#points(Data$time, Data$CHO, pch=5, cex=1.2, col="#542788")
lines(mfit$time, mfit$CHO, lwd=2, lty=2,col="#542788")
legend("topright", c("Nitrite","N2O","Ethanol"), lwd=2, lty=c(1,1,2),col=c("#e08214","#fdb863","#542788"))


dev.off()



Data<-read.csv("batchF_eth.csv",header=TRUE)

scaleFUN <- function(x) sprintf("%.1f", x)
pdf("batchF_eth.pdf", width=4, height=4)
plot(Data$time,Data$Nat, xlab = "Time (min)", ylab = "Concentration (mM)", pch=16, cex=1.2,col="#7f3b08", xlim=c(0,60), ylim=c(0,3.8))
lines(mfit$time, mfit$Nat, lwd=2, col="#7f3b08")
points(Data$time, Data$Nit, pch=16, cex=1.2, col="#e08214")
lines(mfit$time, mfit$Nit, lwd=2, col="#e08214")
points(Data$time, Data$N2O, pch=16, cex=1.2, col="#fdb863")
lines(mfit$time, mfit$N2O, lwd=2, col="#fdb863")
#points(Data$time, Data$CHO, pch=5, cex=1.2, col="#542788")
lines(mfit$time, mfit$CHO, lwd=2, lty=2,col="#542788")
legend("topright", c("Nitrate","Nitrite","N2O","Ethanol"), lwd=2, lty=c(1,1,1,2),col=c("#7f3b08","#e08214","#fdb863","#542788"))

dev.off()

```


```{r barplot}

Data<-read.csv("eth_vmax.csv",header=TRUE)
library(ggplot2)
library(plyr)
library(reshape2)

#barplot(Data, beside=TRUE)
ace<-Data[1:6,]
eth<-Data[7:12,]
met<-Data[13:18,]
mix<-Data[19:24,]
p<-ggplot(Data, aes(x=Batch, y=Rate, fill=Nox)) +
  geom_bar(stat="identity", position=position_dodge())+ scale_fill_manual(values=c("#e08214",'#fdb863',"#fee0b6"))+ geom_errorbar(aes(ymin=Rate-stdev, ymax=Rate+stdev), width=.2,position=position_dodge(.9))+ theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=16))#co
p

pdf("vmax_met.pdf", width=4.5, height=3)
p
dev.off()
#geom_errorbar(aes(ymin=value-stdev, ymax=value-stdev), width=.2,position=position_dodge(.9))+
```



```{r kin}
library(FME)

pars<- list (ka1=0.01, ka2=0.01, ka3=0.01)

solveDnra <- function(pars, times=seq(0,100, by=0.05)){
  
  derivs <- function(t, state, pars){
      with(as.list(c(state, pars)),{
    

      r1<-0.01968* Nat/(Nat+ka1) * CHO/(CHO+0.01)
      r2<-0.0086* Nit/(Nit+ka2) * CHO/(CHO+0.01)
      r3<-0.1527* N2O/(N2O+ka3) * CHO/(CHO+0.01)
      rsum<-r1+r2+r3

      #reaction stoichiometry for ethanol
      dNat<- -2.07*r1*r1/rsum
      dNit<- 1.87*r1*r1/rsum-1.48*r2*r2/rsum
      dN2O<- 0.64*r2*r1/rsum-0.78*r3*r3/rsum
      dCHO<- -0.78*r1*r1/rsum-0.65*r2*r2/rsum-0.46*r3*r3/rsum

          return(list(c(dNat, dNit,dN2O,dCHO)))
      })
  }
times=seq(0,100, by=0.02)
state<-c(Nat=1.42, Nit=0, N2O=0, CHO=1.042)
#solved the mode
  ox<-ode(y=state, times=times, func=derivs, parms=pars)

data.frame(ox[,1:5])
}

output<-solveDnra(pars)  
R<-(1.42-output[51,2]) 
##plotting
#pdf("dnra_cyb_lowCN.pdf", width=5, height=4)
plot(output$time,output$Nat, type = "l",xlab = "Time (h)", ylab = "Concentration (mM)", lwd=3,col="#7f3b08", xlim=c(0,100), ylim=c(0,2))
lines(output$time,output$Nit, lwd=3, col="#e08214")
lines(output$time,output$N2O, lwd=3, col="#fdb863")
legend("topright", c("Nat","Nit","N2O"),lwd=3, lty=c(1,1,1), col=c("#7f3b08","#e08214","#fdb863"))

```


#global sensitivity analysis of gmax and kd
```{r sen}

library(FME)
parRanges <- data.frame(min = c(0.001,0.001,0.001,0.001), max = c(0.1,0.1,0.1,0.1))
rownames(parRanges) <- c("k1","k2","k3","k4")
parRanges

#get sensitivity of vmax
tout <- 0:100  # run the model for 100 times (num)

print(system.time(sR <- sensRange(func = solveDnra, parms = pars, dist ="grid", sensvar = c("Nat", "Nit","N2O","CHO"), parRange = parRanges[4,], num = 100)))

head(summary(sR))

# plotting the result
summ.sR <- summary(sR)

#pdf("Eth_sens_ka3.pdf", width=6, height=6)
par(mfrow=c(2, 2))
plot(summ.sR, xlab = "Time (min) ", ylab = "mM", mfrow = NULL,quant = TRUE, col = c("#fdb863","#7f3b08"), legpos = "topright")
#plot(summ.sR, xlab = "Time (min) ", ylab = "mM", mfrow = NULL,quant = TRUE, col = c("#b2abd2", "#2d004b"), legpos = "topright")
mtext(outer = TRUE, line = -1, side = 3, "Sensitivity to Kd1 ", cex = 1)
#dev.off()
```


# fitting batch F data

```{r kin}
library(FME)

pars<- list (vmax1=0.0098,vmax2=0.0018, vmax3=0.0039)

solveDnra <- function(pars, times=seq(0,100, by=0.05)){
  
  derivs <- function(t, state, pars){
      with(as.list(c(state, pars)),{

      r1<-vmax1* Nat/(Nat+0.01) * CHO/(CHO+0.01)
      r2<-vmax2* Nit/(Nit+0.01) * CHO/(CHO+0.01)
      r3<-vmax3* N2O/(N2O+0.01) * CHO/(CHO+0.01)
      rsum<-r1+r2+r3
      #reaction stoichiometry for methanol
      #dNat<- -1.46*r1*r1/rsum
      #dNit<- 1.26*r1*r1/rsum-1.11*r2*r2/rsum
      #dN2O<- 0.46*r2*r2/rsum-0.60*r3*r3/rsum
      #dCHO<- -1.35*r1*r1/rsum-1.17*r2*r2/rsum-0.87*r3*r3/rsum
      
      #reaction stoichiometry for ethanol
      #dNat<- -2.07*r1
      #dNit<- 1.87*r1-1.48*r2
      #dN2O<- 0.64*r2-0.78*r3
      #dCHO<- -0.78*r1-0.65*r2-0.46*r3
     
       #reaction stoichiometry for acetate
      dNat<- -2.59*r1
      dNit<- 2.39*r1-1.79*r2
      dN2O<- 0.8*r2-0.94*r3
      dCHO<- -1.3*r1-1.05*r2-0.74*r3
    return(list(c(dNat, dNit,dN2O,dCHO, r1,r2,r3,rsum)))
      })
  }
times=seq(0,100, by=0.02)
state<-c(Nat=1.12, Nit=1.14, N2O=0, CHO=1.563,r1=0,r2=0,r3=0,rsum=0)
#solved the mode
  ox<-ode(y=state, times=times, func=derivs, parms=pars)

data.frame(ox[,1:9])
}

output<-solveDnra(pars)  
output$R1<-1.3*output$r1*output$r1/output$rsum  
output$R2<-1.05*output$r2*output$r2/output$rsum 
output$R3<-0.74*output$r3*output$r3/output$rsum 
##plotting
#pdf("batchF_ace_ratio.pdf", width=5, height=4.5)
plot(output$time,output$R1, type = "l",xlab = "Time (h)", ylab = "Concentration (mM)", lwd=3,col="#7f3b08", xlim=c(0,60), ylim=c(0,1))
lines(output$time,output$R2, lwd=3, col="#e08214")
lines(output$time,output$R3, lwd=3, col="#fdb863")
#lines(output$time, output$CHO,lwd=3,lty=2, col="#8073ac" )
legend("topright", c("Nat","Nit","N2O"),lwd=3, lty=c(1,1,1), col=c("#7f3b08","#e08214","#fdb863"))

#dev.off()

```

```{r area}

library(ggplot2)
library(reshape2)
newdf<-data.frame(time=output$time)
newdf$rs1<-output$R3
newdf$rs2<-output$R2
newdf$rs3<-output$R1
newdf<-newdf[-1,]
df<-reshape2::melt(newdf, id.var=c("time"))
p2 <- ggplot() + geom_area(aes(y = value, x = time, fill = variable), data = df,
                           stat="identity", position = position_stack(reverse = T))+ scale_x_continuous(name = 'Time (min) ',limits = c(0,100))+ 
scale_y_continuous(name = 'C consumption (mM) ',limits = c(0,1))+ scale_fill_manual(values=c("#fdb863","#e08214","#7f3b08"))+ theme_linedraw()+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=12))#co

pdf("batchF_consum_ethanol.pdf", width=4.5, height=3)
p2
dev.off() 

```


##fitting

```{r data}


Data<-read.csv("batchF_ace.csv",header=TRUE)

Objective <- function(x, parset = names(x)) {
 pars[parset] <- x
 tout <- seq(0, 30, by = 0.05) ## output times
 out <- solveDnra(pars, tout)
 return(modCost(model = out, obs = Data))## Model cost
}


#parameters are constrained to be >0
print(system.time(Fit <- modFit(p = c( vmax1=0.02, vmax2=0.03,vmax3=0.02),
 f = Objective, lower = c(0.0,0.0,0.0))))

summary(Fit)

```


```{r mcmc}
SF<-summary(Fit)
SF
#initial model error variance (var0)
SF[]

Var0 <-SF$modVariance
covIni <-SF$cov.scaled*2.4^2/3 #length of paramerers (p=3)
MCMC <-modMCMC(p=coef(Fit), f= Objective, jump =covIni, var0 =Var0, wvar0 =1,niter=1000)

#MCMC parameter values per iteration
plot(MCMC, Full=TRUE)
#plot both parameters as a function of one another
pairs(MCMC)

#generate cumulative quantile plot
MC<-as.mcmc(MCMC$pars)
cumuplot(MC)
#covariances based on generated parameters

cov(MCMC$pars)

```

#global sensitivity analysis of gmax and kd
```{r sen}

library(FME)
parRanges <- data.frame(min = c(0.0049,0.002,0.002), max = c(0.0147,0.006,0.006))
rownames(parRanges) <- c("vmax1","vmax2","vmax3")
parRanges

#get sensitivity of vmax
tout <- 0:100  # run the model for 100 times (num)

print(system.time(sR <- sensRange(func = solveDnra, parms = pars, dist ="grid", sensvar = c("Nat", "Nit","N2O","CHO"), parRange = parRanges[2,], num = 100)))

head(summary(sR))

# plotting the result
summ.sR <- summary(sR)

pdf("Eth_sens_vmax2_cyb.pdf", width=6, height=6)
par(mfrow=c(2, 2))
#plot(summ.sR, xlab = "Time (min) ", ylab = "mM", mfrow = NULL,quant = TRUE, col = c("#fdb863","#7f3b08"), legpos = "topright")
plot(summ.sR, xlab = "Time (min) ", ylab = "mM", mfrow = NULL,quant = TRUE, col = c("#b2abd2", "#2d004b"), legpos = "topright")
mtext(outer = TRUE, line = -1, side = 3, "Sensitivity to Kd1 ", cex = 1)
dev.off()
```




```{r plot}

pars[c("vmax1","vmax2","vmax3")]<-Fit$par
output<-solveDnra(pars)  

mfit<-as.data.frame(output[, 1:5])
colnames(mfit) <- c("time", "Nat","Nit","N2O","CHO")
head(mfit)



pdf("batchF_eth_kin.pdf", width=4, height=4)
plot(Data$time,Data$Nat, xlab = "Time (min)", ylab = "Concentration (mM)", pch=16, cex=1.2,col="#7f3b08", xlim=c(0,80), ylim=c(0,3))
lines(mfit$time, mfit$Nat, lwd=2, col="#7f3b08")
points(Data$time, Data$Nit, pch=16, cex=1.2, col="#e08214")
lines(mfit$time, mfit$Nit, lwd=2, col="#e08214")
points(Data$time, Data$N2O, pch=16, cex=1.2, col="#fdb863")
lines(mfit$time, mfit$N2O, lwd=2, col="#fdb863")

legend("topleft", c("NO3","NO2","N2O"), lwd=2, lty=c(1,1,1),col=c("#7f3b08","#e08214","#fdb863"))

dev.off()
```

